# database/models.py
from sqlalchemy import Boolean, Column, DateTime, ForeignKey, Integer, String
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from poghiamo.database.engine import Base


class User(Base):
    """Registered user. Artists, follows and region preferences arrive in phase 2."""

    __tablename__ = "users"

    id = Column(Integer, primary_key=True)
    username = Column(String, unique=True, nullable=False, index=True)
    hashed_password = Column(String, nullable=False)
    is_admin = Column(Boolean, default=False, nullable=False)
    created_at = Column(DateTime, default=func.now())
    # Timestamp of the last events-feed visit, for the "new since last visit" marker.
    last_seen_events_at = Column(DateTime, nullable=True)

    tokens_created = relationship(
        "InviteToken", foreign_keys="InviteToken.created_by", back_populates="creator"
    )


class InviteToken(Base):
    """Single-use invite token generated by an admin.

    Consumed at registration by the first user who signs up with it.
    Tokens expire 7 days after creation if unused; revoked ones are
    soft-deleted to preserve the audit trail. created_by is nullable so
    used tokens can survive their creator's account deletion.
    """

    __tablename__ = "invite_tokens"

    id = Column(Integer, primary_key=True)
    token = Column(String, unique=True, nullable=False, index=True)
    created_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    used_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    revoked = Column(Boolean, default=False, nullable=False)
    created_at = Column(DateTime, default=func.now())
    used_at = Column(DateTime, nullable=True)

    creator = relationship("User", foreign_keys=[created_by], back_populates="tokens_created")
    used_by_user = relationship("User", foreign_keys=[used_by])
