# database/models.py
import json

from sqlalchemy import (
    Boolean,
    Column,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Time,
    UniqueConstraint,
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from poghiamo.database.engine import Base


class User(Base):
    """Registered user."""

    __tablename__ = "users"

    id = Column(Integer, primary_key=True)
    username = Column(String, unique=True, nullable=False, index=True)
    hashed_password = Column(String, nullable=False)
    is_admin = Column(Boolean, default=False, nullable=False)
    created_at = Column(DateTime, default=func.now())
    # Timestamp of the last events-feed visit, for the "new since last visit" marker.
    last_seen_events_at = Column(DateTime, nullable=True)
    # Areas of interest: whole regions (names) and/or single provinces (sigle),
    # both JSON lists. An event matches if its region OR its province is
    # selected; both empty = all of Italy (see geo.area_matches).
    _regions = Column("regions", String, nullable=True)
    _provinces = Column("provinces", String, nullable=True)

    tokens_created = relationship(
        "InviteToken", foreign_keys="InviteToken.created_by", back_populates="creator"
    )
    follows = relationship("Follow", back_populates="user")

    @property
    def regions(self) -> list[str]:
        if not self._regions:
            return []
        return json.loads(self._regions)

    @regions.setter
    def regions(self, value: list[str]):
        self._regions = json.dumps(value) if value else None

    @property
    def provinces(self) -> list[str]:
        if not self._provinces:
            return []
        return json.loads(self._provinces)

    @provinces.setter
    def provinces(self, value: list[str]):
        self._provinces = json.dumps(value) if value else None


class InviteToken(Base):
    """Single-use invite token generated by an admin.

    Consumed at registration by the first user who signs up with it.
    Tokens expire 7 days after creation if unused; revoked ones are
    soft-deleted to preserve the audit trail. created_by is nullable so
    used tokens can survive their creator's account deletion.
    """

    __tablename__ = "invite_tokens"

    id = Column(Integer, primary_key=True)
    token = Column(String, unique=True, nullable=False, index=True)
    created_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    used_by = Column(Integer, ForeignKey("users.id"), nullable=True)
    revoked = Column(Boolean, default=False, nullable=False)
    created_at = Column(DateTime, default=func.now())
    used_at = Column(DateTime, nullable=True)

    creator = relationship("User", foreign_keys=[created_by], back_populates="tokens_created")
    used_by_user = relationship("User", foreign_keys=[used_by])


class Artist(Base):
    """Canonical artist record, shared across users.

    Identity spine is the MusicBrainz MBID once resolved; dedup falls back to
    the normalized name. Per-source handles are filled lazily by the phase-3
    adapters and by the phase-5 Spotify connector.
    """

    __tablename__ = "artists"

    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    name_normalized = Column(String, nullable=False, index=True)
    mbid = Column(String, unique=True, nullable=True)
    country = Column(String, nullable=True)
    image_url = Column(String, nullable=True)
    deezer_id = Column(Integer, nullable=True, index=True)
    # Per-source handles (phase 3+), all optional:
    rockol_id = Column(String, nullable=True)
    ticketsms_slug = Column(String, nullable=True)
    dice_slug = Column(String, nullable=True)
    tm_attraction_id = Column(String, nullable=True)
    spotify_id = Column(String, nullable=True)
    # MusicBrainz enrichment: pending -> resolved | unmatched
    resolution_status = Column(String, default="pending", nullable=False)
    created_at = Column(DateTime, default=func.now())
    # Last time the events pipeline scanned this artist (drives the sweep cadence).
    last_scanned_at = Column(DateTime, nullable=True)


class Follow(Base):
    """User → artist follow.

    Rows are NEVER deleted: an explicit unfollow sets state='removed', which
    future Spotify syncs must respect (a synced artist the user removed in-app
    stays removed). Re-following flips the same row back to 'active'.
    """

    __tablename__ = "follows"
    __table_args__ = (UniqueConstraint("user_id", "artist_id", name="uq_follow_user_artist"),)

    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    artist_id = Column(Integer, ForeignKey("artists.id"), nullable=False, index=True)
    state = Column(String, default="active", nullable=False)  # active | removed
    source = Column(String, default="manual", nullable=False)  # manual | spotify
    created_at = Column(DateTime, default=func.now())
    removed_at = Column(DateTime, nullable=True)

    user = relationship("User", back_populates="follows")
    artist = relationship("Artist")


class Event(Base):
    """Canonical concert, shared across users and sources.

    Italy-only (adapters drop foreign dates at their boundary). Dedup key is
    (artist_id, date, city_normalized); the same gig arriving from several
    sources collapses onto one Event with one EventSource row per source.
    Stale events (unseen recently) are kept until their date passes; they are
    never silently removed.
    """

    __tablename__ = "events"
    __table_args__ = (
        UniqueConstraint("artist_id", "date", "city_normalized", name="uq_event_dedup"),
    )

    id = Column(Integer, primary_key=True)
    artist_id = Column(Integer, ForeignKey("artists.id"), nullable=False, index=True)
    date = Column(Date, nullable=False, index=True)
    time = Column(Time, nullable=True)
    venue = Column(String, nullable=True)
    city = Column(String, nullable=True)
    city_normalized = Column(String, nullable=False, default="")
    province = Column(String, nullable=True)  # sigla, e.g. "MI"
    region = Column(String, nullable=True)
    lat = Column(Float, nullable=True)
    lon = Column(Float, nullable=True)
    title = Column(String, nullable=True)
    first_seen_at = Column(DateTime, default=func.now())
    last_seen_at = Column(DateTime, default=func.now())

    artist = relationship("Artist")
    sources = relationship("EventSource", back_populates="event", cascade="all, delete-orphan")


class EventSource(Base):
    """One source's view of an Event (its own id and ticket link)."""

    __tablename__ = "event_sources"
    __table_args__ = (UniqueConstraint("event_id", "source", name="uq_event_source"),)

    id = Column(Integer, primary_key=True)
    event_id = Column(Integer, ForeignKey("events.id"), nullable=False, index=True)
    source = Column(String, nullable=False)  # ticketsms | dice | ticketmaster | rockol
    source_event_id = Column(String, nullable=True)
    ticket_url = Column(String, nullable=True)
    first_seen_at = Column(DateTime, default=func.now())
    last_seen_at = Column(DateTime, default=func.now())

    event = relationship("Event", back_populates="sources")


class ScanLog(Base):
    """Per-source health record for one artist scan, for observability."""

    __tablename__ = "scan_logs"

    id = Column(Integer, primary_key=True)
    artist_id = Column(Integer, ForeignKey("artists.id"), nullable=True, index=True)
    source = Column(String, nullable=False)
    status = Column(String, nullable=False)  # ok | error | timeout | disabled | skipped
    found = Column(Integer, default=0)
    message = Column(String, nullable=True)
    ran_at = Column(DateTime, default=func.now(), index=True)


class SavedEvent(Base):
    """A user's bookmark of an Event, shown in the Calendario section.

    Saved events must survive any future event pruning (a user planned around
    them). Deleting a user drops their bookmarks; deleting an event cascades.
    """

    __tablename__ = "saved_events"
    __table_args__ = (UniqueConstraint("user_id", "event_id", name="uq_saved_user_event"),)

    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    event_id = Column(Integer, ForeignKey("events.id"), nullable=False, index=True)
    created_at = Column(DateTime, default=func.now())
